server:
  port: 10001
  context-path: /mysql
  ssl:
    enabled: false
  jetty:
    max-http-post-size: 2097152
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #create|update|create-drop|validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    primary:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.130:3306/journal
      username: root
      password: weidu1314
    secondary:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://www.dimonho.com:3306/ssoserver
      username: root
      password: root123